const actionTypes = {
	REQUEST_TOKEN: 'REQUEST_TOKEN',
	REQUEST_ANIMAL: 'REQUEST_ANIMAL',
	REQUEST_ANIMALS: 'REQUEST_ANIMALS',
	AUTH_LOGIN: 'AUTH_LOGIN',
	AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
	AUTH_SIGNOUT: 'AUTH_SIGNOUT',
	AUTH_SIGNOUT_ERROR: 'AUTH_SIGNOUT_ERROR'
};

export default actionTypes;
